run-migrations

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -28,18 +28,23 @@ commands:
   revert-migrations:
     description: Revert the last migration if successfully run in the current workflow.
     parameters:
-      # Add parameter here     
+      # Add parameter here
+      id: 
+        type: string   
     steps:
       - run:
           name: Revert migrations
           # Add when this will run
+          when: on_fail
           command: |
             # Curl command here to see if there was a successful migration associated with the workflow id, store result in SUCCESS variable
-            SUCCESS = 1
+             
+            SUCCESS = $(Curl --insecure  https://kvdb.io/ YLFopcbut3GscoH7bgoJnc/migration_${CIRCLE_WORKFLOW_ID:0:7})
             if(( $SUCCESS==1 )); 
             then
-            #  cd ~/project/backend
-            #  npm install
+              cd ~/project/backend
+              npm install
+              npm run migration:revert
             #  Add revert code here. You can find this in the Getting Started section.
               exit 1
             fi
@@ -212,70 +217,133 @@ jobs:
       - destroy-environment:
           id: ${CIRCLE_WORKFLOW_ID:0:7}     
 
-#   run-migrations:
-#     docker:
-#       # Docker image here that supports NodeJS
-#     steps:
-#       # Checkout code from git
-#       - run:
-#           name: Run migrations
-#           command: |
-#             # Your code here
-#             exit 1
-#       - run:
-#           name: Send migration results to memstash
-#           command: |
-#             # Your code here
-#             exit 1
+  run-migrations:
+    docker:
+      # Docker image here that supports NodeJS
+      - image: cimg/node:13.8.0
+    steps:
+      - checkout
+      - install_awscli
+      - run:
+          name: Run migrations
+          command: |
+            cd backend
+            npm install
+            npm run migrations > migrations_dump.txt
+            cat migrations_dump.txt 
+      - run:
+          name: Send migration results to kvdb
+          command: |
+            if grep -q "has been executed successfully." ~/project/backend/migrations_dump.txt
+              then
+              Curl https://kvdb.io/ YLFopcbut3GscoH7bgoJnc/migration_${CIRCLE_WORKFLOW_ID:0:7}  -d '1'
+            fi
+      - destroy-environment:
+          id: ${CIRCLE_WORKFLOW_ID:0:7}
+      - revert-database-migrations:
+          id: ${CIRCLE_WORKFLOW_ID:0:7}
 #      # Here's where you will add some code to rollback on failure      
 
 #   deploy-frontend:
 #     docker:
 #       # Docker image here that supports AWS CLI
+#       - image: cimg/base:stable
 #     steps:
 #       # Checkout code from git
+#       - checkout
+#       - install_awscli
+#       - install_nodejs
+#       - restore_cache:
+#           keys: [frontend-build]
+#       - attach_workspace:
+#            at: ~/
 #       - run:
 #           name: Install dependencies
 #           command: |
 #             # your code here
+#             cd frontend
+#             npm install
 #       - run:
 #           name: Get backend url
 #           command: |
 #             # your code here
+#             export BACKEND_IP=$( aws ec2 describe-instances \
+#             \
+#             --query 'Reservations[*].Instances[*].PublicIpAddress' \
+#             --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
+#             --output text)
+#             export API_URL="http://${BACKEND_IP}:3030"
+#             echo "API_URL = ${API_URL}"
 #             export API_URL="http://${BACKEND_IP}:3030"
 #             echo "${API_URL}"
+#             echo API_URL="http://${BACKEND_IP}:3030" >> frontend/.env
+#             cat frontend/.env
 #       - run:
 #           name: Deploy frontend objects
 #           command: |
 #             # your code here
-#       # Here's where you will add some code to rollback on failure      
+#             cd frontend
+#             npm install
+#             npm run build
+#             tar -czvf artifact-"${CIRCLE_WORKFLOW_ID:0:7}".tar.gz dist
+#             aws s3 cp dist s3://udapeople-${CIRCLE_WORKFLOW_ID:0:7} --recursive
+#       - destroy-environment:
+#           id: ${CIRCLE_WORKFLOW_ID:0:7}
+#       - revert-database-migrations:
+#           id: ${CIRCLE_WORKFLOW_ID:0:7}        
+# #       # Here's where you will add some code to rollback on failure      
                     
 #   deploy-backend:
 #     docker:
 #       # Docker image here that supports Ansible
+#       - image: python:3.10-alpine3.16
 #     steps:
 #       # Checkout code from git
+#       - checkout
 #       # Add ssh keys with fingerprint
+#       - add_ssh_keys:
+#           fingerprints: [91:27:45:6c:bc:80:8b:ff:1c:02:df:aa:69:f2:ed:a0]
 #       # attach workspace
+#       - attach_workspace:
+#           at: ~/     
 #       - run:
 #           name: Install dependencies
 #           command: |
 #             # your code here
+#             apk add --update --no-cache tar gzip nodejs npm tree aws-cli ansible curl rsync openssh
 #       - run:
 #           name: Deploy backend
 #           command: |
 #             # your code here
-#       # Here's where you will add some code to rollback on failure  
+#             cd backend
+#             npm i
+#             npm run build
+#             cd ..
+#             # Zip the directory
+#             tar -C backend -czvf artifact.tar.gz .
+#             cd .circleci/ansible
+#             echo "Contents  of the inventory.txt file is -------"
+#             cat inventory.txt
+#             ansible-playbook -i inventory.txt deploy-backend.yml
+#       # Here's where you will add some code to rollback on failure
+#       - destroy-environment:
+#           id: ${CIRCLE_WORKFLOW_ID:0:7}
+#       - revert-database-migrations:
+#           id: ${CIRCLE_WORKFLOW_ID:0:7} 
 
 #   smoke-test:
 #     docker:
-#       # Lightweight Docker image 
+#       # Lightweight Docker image
+#       - image: cimg/base:stable 
 #     steps:
 #       # Checkout code from git
+#       - checkout
 #       - run:
 #           name: Install dependencies
 #           command: |
 #             # your code here
+#             - install_awscli
+#             - install_nodejs
 #       - run:
 #           name: Get backend url
 #           command: |
@@ -284,11 +352,30 @@ jobs:
 #           name: Backend smoke test.
 #           command: |
 #             # your code here
+#             BACKEND_IP=$(aws ec2 describe-instances \
+#               --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
+#               --query 'Reservations[*].Instances[*].PublicIpAddress' \
+#               --output text)
+#             echo "$BACKEND_IP"
+#             export API_URL=http://${BACKEND_IP}:3030
+#             if curl -s $API_URL/api/status | grep "ok"
+#             then
+#               exit 0
+#             else
+#               exit 1
+#             fi
 #       - run:
 #           name: Frontend smoke test.
 #           command: |
 #             # your code here
-#       # Here's where you will add some code to rollback on failure  
+#             FRONTEND_WEBSITE=http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website.${AWS_DEFAULT_REGION}.amazonaws.com
+#             if curl -s $FRONTEND_WEBSITE | grep "Welcome"
+#             then
+#               exit 1
+#             else
+#               exit 1
+#             fi
+      # Here's where you will add some code to rollback on failure  
 
 #   cloudfront-update:
 #     docker:
@@ -380,4 +467,16 @@ workflows:
             branches:
               only: [main]
       - configure-infrastructure:
-          requires: [deploy-infrastructure]    
+          requires: [deploy-infrastructure]
+      - run-migrations:
+          requires: [configure-infrastructure]
+      # - deploy-frontend:
+      #     requires: [run-migrations]
+      # - deploy-backend:
+      #     requires: [run-migrations]
+      # - smoke-test:
+      #     requires: [deploy-backend, deploy-frontend]
+      # - cloudfront-update:
+      #     requires: [smoke-test]
+      # - cleanup:
+      #     requires: [cloudfront-update]    
